# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

BOX_IMAGE = "fedora35arm"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  #config.ssh.private_key_path = "id_rsa"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  #config.ssh.pty = true
  config.vm.synced_folder ".", "/vagrant1", disabled: true
  (1..NODE_COUNT).each do |i|
    config.vm.define "fedora35arm#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "fedora35arm#{i}"
      subconfig.vm.provider "vmware_desktop" do |vmware|
        vmware.vmx["ethernet0.pcislotnumber"] = "33"
        vmware.vmx["memsize"] = "2048"
        vmware.vmx["numvcpus"] = "2"
        vmware.gui = true
      end
    end
  end
end